/**
 * @packageDocumentation
 * @module Databind
 */

export enum DeserializationFeature {
  FAIL_ON_UNKNOWN_PROPERTIES,
  FAIL_ON_NULL_FOR_PRIMITIVES,
  FAIL_ON_MISSING_CREATOR_PROPERTIES,
  FAIL_ON_NULL_CREATOR_PROPERTIES,
  FAIL_ON_UNRESOLVED_OBJECT_IDS,
  ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT,
  ACCEPT_EMPTY_STRING_AS_NULL_OBJECT,
  ACCEPT_FLOAT_AS_INT,
  SET_DEFAULT_VALUE_FOR_PRIMITIVES_ON_NULL,
  SET_DEFAULT_VALUE_FOR_NUMBER_ON_NULL,
  SET_DEFAULT_VALUE_FOR_STRING_ON_NULL,
  SET_DEFAULT_VALUE_FOR_BOOLEAN_ON_NULL,
  SET_DEFAULT_VALUE_FOR_BIGINT_ON_NULL
}
