/**
 * @packageDocumentation
 * @module Databind
 */

export enum MapperFeature {
  SET_DEFAULT_VALUE_FOR_PRIMITIVES_ON_NULL,
  SET_DEFAULT_VALUE_FOR_NUMBER_ON_NULL,
  SET_DEFAULT_VALUE_FOR_STRING_ON_NULL,
  SET_DEFAULT_VALUE_FOR_BOOLEAN_ON_NULL,
  SET_DEFAULT_VALUE_FOR_BIGINT_ON_NULL
}
