/**
 * @packageDocumentation
 * @module Databind
 */

export enum SerializationFeature {
  FAIL_ON_SELF_REFERENCES,
  ORDER_MAP_ENTRIES_BY_KEYS,
  WRITE_NAN_AS_ZERO,
  WRITE_POSITIVE_INFINITY_AS_NUMBER_MAX_SAFE_INTEGER,
  WRITE_POSITIVE_INFINITY_AS_NUMBER_MAX_VALUE,
  WRITE_NEGATIVE_INFINITY_AS_NUMBER_MIN_SAFE_INTEGER,
  WRITE_NEGATIVE_INFINITY_AS_NUMBER_MIN_VALUE,
  WRITE_DATES_AS_TIMESTAMPS
}
